config/routes.rb
Bayadligid::Application.routes.draw do
  get "applied_loan_details/index"

  get "applied_loan_details/new"

  get "applied_loan_details/edit"

  get "applied_loan_details/create"

  get "applied_loan_details/update"

  get "applied_loan_details/destroy"

  resources :companies do
  	resources :branches
  	resources :payrolls do
		member do
			get 'daily_payroll'
			get 'daily_payroll_details'
			get 'monthly_payroll'
			get 'monthly_payroll_details'
			get 'prooflist'
			get 'payslip'
			get 'two_by_two'
		end
	end
  end

  

  resources :loans
  resources :employees do
	  resources :applied_loans do
	    resources :applied_loan_details
	  end
  end

  resources :holidays do
  	collection do
  		get 'reset'
  	end
  end

  match '/:action', :controller => 'application'








  root :to => 'application#index'


end

app/models/branch.rb
# == Schema Information
#
# Table name: branches
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  company_id :integer         not null
#  created_at :datetime
#  updated_at :datetime
#

class Branch < ActiveRecord::Base
  belongs_to :company
  has_many :employees, :dependent=>:destroy
  has_many :users, :through=>:company
  validates_presence_of :name, :company
  
  def pretty_branches
  	self.company.name + " - " + self.name
  end
  
  def self.available_branches(user_id)
	b = Branch.joins(:users).where("users.id=#{user_id}").order("companies.name, branches.name").includes(:company)
	return b		
  end
end


app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.where(:company_id=>params[:company_id]).order(:name).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @branches }
    end
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    @branch = Branch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/new
  # GET /branches/new.json
  def new
    @branch = Branch.new(:company_id => params[:company_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @branch }
    end
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(params[:branch])
		@branch.company_id = params[:company_id]
    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch.company, notice: 'Branch was successfully created.' }
        format.json { render json: @branch, status: :created, location: @branch }
      else
        format.html { render action: "new" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /branches/1
  # PUT /branches/1.json
  def update
    @branch = Branch.find(params[:id])

    respond_to do |format|
      if @branch.update_attributes(params[:branch])
        format.html { redirect_to @branch.company, notice: 'Branch was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch = Branch.find(params[:id])
    @branch.destroy

    respond_to do |format|
      format.html { redirect_to company_url(params[:company_id]) }
      format.json { head :ok }
    end
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for([@branch.company,@branch]) do |f| %>
  <% if @branch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@branch.errors.count, "error") %> prohibited this branch from being saved:</h2>

      <ul>
      <% @branch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name, "Branch" %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/branches/edit.html.erb
<h1>Editing branch</h1>

<%= render 'form' %>

<div class="extra">
	<%= link_to 'Show', [@branch.company,@branch] %> |
	<%= link_to 'Back', company_branches_path(@branch.company) %>
</div>

app/views/branches/index.html.erb
<h1>Listing branches </h1>

<table>
  <tr>
    <th>Branch</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @branches.each do |branch| %>
  <tr>
    <td><%= branch.name %></td>
    <td><%= link_to 'Show', [branch.company, branch] %></td>
    <td><%= link_to 'Edit', edit_company_branch_path(branch.company, branch) %></td>
    <td><%= link_to 'Destroy', company_branch_path(branch.company, branch), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<div class="extra">
	<%= link_to 'New Branch', new_company_branch_path(params[:company_id]) %>
	<%= link_to 'Back', company_url(params[:company_id]) %>
</div>

app/views/branches/new.html.erb
<h1>New branch</h1>

<%= render 'form' %>

<div class="extra">
	<%= link_to 'Back', company_branches_path(params[:company_id]) %>
</div>

app/views/branches/show.html.erb
<div class="show">
	<p id="notice"><%= notice %></p>

	<p>
		<b>Branch:</b>
		<%= @branch.name %>
	</p>

	<p>
		<b>Employees:</b>
		<ul>
		<% for e in @branch.employees %>
			<li> <%= link_to (e.first_name + " "+ e.last_name), e %> </li>
		<% end %>
		</ul>
	</p>
</div>
<div class="extra">
	<%= link_to 'Edit', edit_company_branch_path(@branch.company,@branch) %> |
	<%= link_to 'Back', company_path(@branch.company) %>
</div>