config/routes.rb
Bayadligid::Application.routes.draw do
  get "applied_loan_details/index"

  get "applied_loan_details/new"

  get "applied_loan_details/edit"

  get "applied_loan_details/create"

  get "applied_loan_details/update"

  get "applied_loan_details/destroy"

  resources :companies do
  	resources :branches
  	resources :payrolls do
		member do
			get 'daily_payroll'
			get 'daily_payroll_details'
			get 'monthly_payroll'
			get 'monthly_payroll_details'
			get 'prooflist'
			get 'payslip'
			get 'two_by_two'
		end
	end
  end

  

  resources :loans
  resources :employees do
	  resources :applied_loans do
	    resources :applied_loan_details
	  end
  end

  resources :holidays do
  	collection do
  		get 'reset'
  	end
  end

  match '/:action', :controller => 'application'








  root :to => 'application#index'


end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id               :integer         not null, primary key
#  first_name       :string(255)     not null
#  middle_name      :string(255)     not null
#  last_name        :string(255)     not null
#  address          :text
#  phone_no         :string(255)
#  mobile_no        :string(255)
#  birthdate        :date
#  date_hired       :date
#  date_regularized :date
#  date_left        :date
#  sss_no           :string(255)
#  philhealth_no    :string(255)
#  pagibig_no       :string(255)
#  civil_status     :string(255)
#  status           :string(255)     default("Active"), not null
#  branch_id        :integer         not null
#  created_at       :datetime
#  updated_at       :datetime
#  employee_type    :string(255)
#  rate             :float
#

class Employee < ActiveRecord::Base
  belongs_to :branch
  has_one :company, :through=>:branch
  has_many :payroll_details, :dependent=>:destroy
  has_many :applied_loans, :dependent=>:destroy
  has_many :users, :through=>:company
  
  validates_presence_of :first_name, :middle_name, :last_name, :status, :branch
  validates_numericality_of :rate, :greater_than => 0
  #validates_uniqueness_of :sss_no, :philhealth_no, :pagibig_no
  
  
	
	
  before_save :set_date_regularized
  
  @@loan_names = nil
  @balance = nil
  
  def complete_name
  	self.last_name + ", " + self.first_name
  end
  
  def full_name
  	complete_name + ' ' + self.middle_name
  end
  
  def self.employee_types
		return ["Monthly", "Daily"]
  end
  
  def self.statuses
  	return ["Active", "Fired", "Resigned"]
  end
  
  def self.civil_statuses
  	return ["Single", "Married", "Widowed"]
  end
  
	def self.company_employees(company_id, payroll_type)
		return Employee.joins(:branch, :company).where("companies.id = ? AND employees.employee_type = ?",company_id,payroll_type).order("branches.name").order(:last_name)
	end
	
	def remaining_balance(loan_name)
		load_loan_names if @@loan_names.nil?
		load_loan_balances if @balances.nil?
		return "%.2f" % @balances[loan_name]
	end
	
	private 
		# def create_monthly_rate
			# MonthlyRate.create(:employee_id=>self.id, :rate=>self.monthly_salary, :date_started=>Date.today.beginning_of_month)
		# end
		
		# def update_monthly_rate
			# mRate = MonthlyRate.find_by_employee_id_and_date_ended(self.id, nil)
			# if(!mRate.nil? && mRate.rate != self.monthly_salary)
				# MonthlyRate.update(mRate,:date_ended=>Date.today.end_of_month)
			# end
			# MonthlyRate.create(:employee_id=>self.id, :rate=>self.monthly_salary, :date_started=>Date.today.end_of_month+1.days)

		# end
		
		def set_date_regularized
			self.date_regularized = self.date_hired + 6.months
		end
		
		def load_loan_names
			@@loan_names = {}
			loans = Loan.select([:id, :name])
			loans.each { |l| @@loan_names[l.id] = l.name }
		end
		
		def load_loan_balances
		  @balances = {}
			
			@@loan_names.each { |key, value| @balances[value] = 0.0 }
			
			als = self.applied_loans.where("#{:date_ended} > '#{Date.today}'")
			
			als.each do |al|
				@balances[@@loan_names[al.loan_id]] += al.remaining_balance
			end
		end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
   	emp = Employee.joins(:users).where("users.id=?", session[:user_id]).includes(:branch, :company)
   	@employees = []
   	emp.each {|e| @employees << e}
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])
	  @applied_loans = @employee.applied_loans
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new
	@available_branches = Branch.available_branches(session[:user_id])
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
    @available_branches = Branch.available_branches(session[:user_id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])
		@available_branches = Branch.available_branches(session[:user_id])
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])
		@available_branches = Branch.available_branches(session[:user_id])
    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :ok }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
	def pretty_select_for_branches(branches)
	
		cur_company_id = -1
		last_company_name = ""
		i = 0
		result = ""
		result += "<select id='employee_branch_id' name='employee[branch_id]'>"
		
		branches.each do |branch|
			if cur_company_id != branch.company_id
				if i > 0 
					result += "</optgroup>"
				end
				cur_company_id = branch.company_id
				last_company_name = branch.company.name
				result += "<optgroup label='#{last_company_name}'>"
			
				i += 1
			end
			result += "<option value='#{branch.id}'>#{branch.name}</option>"
		end
		result += "</optgroup>"
		result += "</select>"
		return raw(result)
	end
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :branch %>
    <%= pretty_select_for_branches @available_branches %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %>
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
	<%= f.label :employee_type %>
	<% Employee.employee_types.each do |e| %>
	  <%= f.radio_button :employee_type, e, :checked=>"checked" %> <%= e %>
	  
    <% end %>
	
  </div>
  
  <div class="field">
    <%= f.label :rate %>
    <%= f.number_field :rate, :step=>0.01 %>
  </div>
  
  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :phone_no %>
    <%= f.text_field :phone_no %>
  </div>
  <div class="field">
    <%= f.label :mobile_no %>
    <%= f.text_field :mobile_no %>
  </div>
  <div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate, :start_year=>Time.now.year-40, :end_year=>Time.now.year-10 %>
  </div>
  <div class="field">
    <%= f.label :date_hired %>
    <%= f.date_select :date_hired, :start_year=>Time.now.year-15, :end_year=>Time.now.year %>
  </div>
  
  <div class="field">
    <%= f.label :sss_no %>
    <%= f.text_field :sss_no %>
  </div>
  <div class="field">
    <%= f.label :philhealth_no %>
    <%= f.text_field :philhealth_no %>
  </div>
  <div class="field">
    <%= f.label :pagibig_no %>
    <%= f.text_field :pagibig_no %>
  </div>
  <div class="field">
    <%= f.label :civil_status %>
    <%= f.select :civil_status, Employee.civil_statuses %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>
<div class="extra">
	<%= link_to 'Show', @employee %> |
	<%= link_to 'Back', employees_path %>
</div>

app/views/employees/index.html.erb
<h1>Listing employees</h1>


	<table border=1>
		<tr>
		  <th rowspan="2">Branch</th>
		  <th rowspan="2">Name</th>
		  <th rowspan="2">Type</th>
		  <th rowspan="2">Rate</th>
		  <th colspan="12">Remaining Balance(Loans)</th>
		</tr>
		<tr>
		  <td>HDMF</td>
		  <td>SSS</td>
		  <td>PhilHealth</td>
		  <td>Salary</td>
		  <td>Calamity</td>
		  <td>Cash Advance</td>
		  <td>Other Deductions</td>
		  <td>Losses</td>
		  <td colspan="4">Options</td>
		</tr>
<% cur_company_id = -1 %>
<% @employees.each do |employee| %>


		<% if cur_company_id != employee.branch.company_id %>
		<% cur_company_id = employee.branch.company_id %>
			<tr>
				<td colspan="16"><b><%= employee.branch.company.name %></b></td>
			</tr>
		<% end %>
		<tr>
			<td><%= employee.branch.name %></td>
		  <td><%= employee.complete_name %></td>
		  <td><%= employee.employee_type %></td>
		  <td><%= employee.rate %></td>
		  <td><%= employee.remaining_balance("HDMF") %></td>
		  <td><%= employee.remaining_balance("SSS") %></td>
		  <td><%= employee.remaining_balance("PhilHealth") %></td>
		  <td><%= employee.remaining_balance("Salary") %></td>
		  <td><%= employee.remaining_balance("Calamity") %></td>
		  <td><%= employee.remaining_balance("Cash Advance") %></td>		  		  
		  <td><%= employee.remaining_balance("Other Deductions") %></td>
		  <td><%= employee.remaining_balance("Losses") %></td>
		  <td><%= link_to 'View Employee', employee %></td>
		  <td><%= link_to 'View Applied Loans', employee_applied_loans_path(employee) %></td>
		  <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
		  <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', method: :delete %></td>
		</tr>

<% end %>
	</table>


<br />
<div class="extra">
	<%= link_to 'New Employee', new_employee_path %>
</div>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>
<div class="extra">
	<%= link_to 'Back', employees_path %>
</div>

app/views/employees/show.html.erb

<div class="show left-side-bar">
	<p id="notice"><%= notice %></p>

	<p>
		<b>Branch:</b>
		<%= @employee.branch.name %>
	</p>

	<p>
		<b>First name:</b>
		<%= @employee.first_name %>
	</p>

	<p>
		<b>Middle name:</b>
		<%= @employee.middle_name %>
	</p>

	<p>
		<b>Last name:</b>
		<%= @employee.last_name %>
	</p>

	<p>
		<b>Type:</b>
		<%= @employee.employee_type %>
	</p>

	<p>
		<b>Rate:</b>
		<%= @employee.rate %>
	</p>

	<p>
		<b>Address:</b>
		<%= @employee.address %>
	</p>

	<p>
		<b>Phone no:</b>
		<%= @employee.phone_no %>
	</p>

	<p>
		<b>Mobile no:</b>
		<%= @employee.mobile_no %>
	</p>

	<p>
		<b>Birthdate:</b>
		<%= @employee.birthdate %>
	</p>

	<p>
		<b>Date hired:</b>
		<%= @employee.date_hired %>
	</p>

	<p>
		<b>Date regularized:</b>
		<%= @employee.date_regularized %>
	</p>


	<p>
		<b>Sss no:</b>
		<%= @employee.sss_no %>
	</p>

	<p>
		<b>Philhealth no:</b>
		<%= @employee.philhealth_no %>
	</p>

	<p>
		<b>Pagibig no:</b>
		<%= @employee.pagibig_no %>
	</p>

	<p>
		<b>Civil status:</b>
		<%= @employee.civil_status %>
	</p>

	<p>
		<b>Status:</b>
		<%= @employee.status %>
	</p>
</div>

<div class="right-side-bar">
	<%= render 'applied_loans/index' %>
</div>

<div class="extra" style="clear:left;">
  <a href="<%= new_employee_applied_loan_path(@employee) %>"><input type="button" value="Apply New Loan" /></a>
	<%= link_to 'Edit', edit_employee_path(@employee) %> |
	<%= link_to 'Back', employees_path %>
</div>