config/routes.rb
Bayadligid::Application.routes.draw do
  get "applied_loan_details/index"

  get "applied_loan_details/new"

  get "applied_loan_details/edit"

  get "applied_loan_details/create"

  get "applied_loan_details/update"

  get "applied_loan_details/destroy"

  resources :companies do
  	resources :branches
  	resources :payrolls do
		member do
			get 'daily_payroll'
			get 'daily_payroll_details'
			get 'monthly_payroll'
			get 'monthly_payroll_details'
			get 'prooflist'
			get 'payslip'
			get 'two_by_two'
		end
	end
  end

  

  resources :loans
  resources :employees do
	  resources :applied_loans do
	    resources :applied_loan_details
	  end
  end

  resources :holidays do
  	collection do
  		get 'reset'
  	end
  end

  match '/:action', :controller => 'application'








  root :to => 'application#index'


end

app/models/applied_loan.rb
# == Schema Information
#
# Table name: applied_loans
#
#  id                  :integer         not null, primary key
#  employee_id         :integer         not null
#  loan_id             :integer         not null
#  date_started        :date            not null
#  date_ended          :date            not null
#  amount_per_interval :float           not null
#  original_amount     :float           not null
#  created_at          :datetime
#  updated_at          :datetime
#  interval_type       :string(255)
#

class AppliedLoan < ActiveRecord::Base
  belongs_to :employee
  belongs_to :loan
  has_many :applied_loan_details, :dependent=>:destroy
  
  @@INTERVAL_TYPES = ["Weekly", "Monthly"]
  
  validates_presence_of :date_started, :interval_type, :amount_per_interval, :original_amount
  validate :date_started_cannot_be_greater_than_date_ended
  validates :amount_per_interval, :numericality=>{ :greater_than => 0 }
  validates :original_amount, :numericality=>{ :greater_than => 0 }
	validates :interval_type, :inclusion=>{:in=>@@INTERVAL_TYPES, :message=>"%{value} is not a valid interval type."}
	
  before_create :calculate_date_ended
  after_create :create_applied_loan_details
 
  
  def self.interval_types
  	@@INTERVAL_TYPES
  end
  
	def remaining_balance
		#get sum of paid applied loan details minus the original balance
		paid = self.applied_loan_details.where('date_applied < :date_applied',{:date_applied =>Date.today}).sum(:amount)
		balance = self.original_amount - paid
		#balance = balance > 0 ? balance : 0
    return balance
	end
  
  private 
  	def calculate_date_ended
  		amount = self.original_amount
			@intervals = 0
			
			while amount > 0 
				@intervals += 1
				amount -= self.amount_per_interval 
			end
			
  		if(self.interval_type == "Weekly")
				self.date_ended = self.date_started + (7*(@intervals-1)).days
			elsif(self.interval_type == "Monthly")
  			self.date_ended = get_last_date
  		end
  		
  	end
  	
  	def get_last_date
  		from = self.date_started
  		if from.day <= 10
				day = (@intervals%2==0) ? 25 : 10
				from += ((@intervals-1)/2).months
			elsif from.day <= 25
				day = (@intervals%2==0) ? 10 : 25
				from += (@intervals/2).months
			else
				day = (@intervals%2==0) ? 25 : 10
				from += ((@intervals+1)/2).months
			end
			Date.parse("#{day}/#{from.month}/#{from.year}")
  	end
  	
  	def create_applied_loan_details
  		start_date = self.date_started  	
  		sum = 0
 		  amount = 0
  		if(self.interval_type == "Weekly")
  			@intervals.times do
  			  if sum+self.amount_per_interval > self.original_amount then
  			    amount = self.original_amount - sum
  			  else
  			    amount = self.amount_per_interval
  			  end
  			  sum += self.amount_per_interval  			  
				  AppliedLoanDetail.create(:applied_loan_id=>self.id, :amount=>amount, :date_applied=>start_date)	
				  start_date += 7.days
  			end
			elsif(self.interval_type == "Monthly")
				if(start_date.day <= 10)
					start_day = 10
				elsif(start_date.day <= 25)
					start_day = 25
				elsif(start_date.day > 25) 
					start_day = 10
					start_date += 1.month
				end
				@intervals.times do
  			  if sum+self.amount_per_interval > self.original_amount then
  			    amount = self.original_amount - sum
  			  else
  			    amount = self.amount_per_interval
  			  end
  			  sum += self.amount_per_interval
					d = Date.parse("#{start_day}/#{start_date.month}/#{start_date.year}")				
					if(start_day == 10)
						start_day = 25
					else
						start_day = 10  				
						start_date += 1.month
					end
					AppliedLoanDetail.create(:applied_loan_id=>self.id, :amount=>amount, :date_applied=>d)
				end
			end
  		
  	end
  	
	  def date_started_cannot_be_greater_than_date_ended
	  	if !date_ended.nil? and date_started > date_ended
        errors.add(:date_started, "can't be later than date ended")
      end
	  end
  
end

app/controllers/applied_loans_controller.rb
class AppliedLoansController < ApplicationController
  # GET /applied_loans
  # GET /applied_loans.json
  def index
    @applied_loans = AppliedLoan.find_all_by_employee_id(params[:employee_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applied_loans }
    end
  end

  # GET /applied_loans/1
  # GET /applied_loans/1.json
  def show
    @applied_loan = AppliedLoan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @applied_loan }
    end
  end

  # GET /applied_loans/new
  # GET /applied_loans/new.json
  def new
    @applied_loan = AppliedLoan.new(:employee_id=>params[:employee_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @applied_loan }
    end
  end

  # GET /applied_loans/1/edit
  def edit
    @applied_loan = AppliedLoan.find(params[:id])
  end

  # POST /applied_loans
  # POST /applied_loans.json
  def create
    @applied_loan = AppliedLoan.new(params[:applied_loan])

    respond_to do |format|
      if @applied_loan.save
        format.html { redirect_to [@applied_loan.employee, @applied_loan], notice: 'Applied loan was successfully created.' }
        format.json { render json: @applied_loan, status: :created, location: @applied_loan }
      else
        format.html { render action: "new" }
        format.json { render json: @applied_loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applied_loans/1
  # PUT /applied_loans/1.json
  def update
    @applied_loan = AppliedLoan.find(params[:id])

    respond_to do |format|
      if @applied_loan.update_attributes(params[:applied_loan])
        format.html { redirect_to [@applied_loan.employee, @applied_loan], notice: 'Applied loan was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @applied_loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applied_loans/1
  # DELETE /applied_loans/1.json
  def destroy
    @applied_loan = AppliedLoan.find(params[:id])
    @applied_loan.destroy

    respond_to do |format|
      format.html { redirect_to employee_url(params[:employee_id]) }
      format.json { head :ok }
    end
  end
  
end

app/helpers/applied_loans_helper.rb
module AppliedLoansHelper
	def employee_full_name(emp_id)
		Employee.find(emp_id).complete_name
	end
end

app/views/applied_loans/_applied_loan_details.html.erb
<% ald = @applied_loan.applied_loan_details.order(:date_applied) %>
<h3>Breakdown (P<%=ald.sum(:amount)%>): <small>(<%= link_to 'Add a breakdown/detail', new_employee_applied_loan_applied_loan_detail_path(@applied_loan.employee_id, @applied_loan)%>)</small></h3>
<ul>
	<% ald.each do |details| %>
			<li>
				<%= details.date_applied %> - <%= details.amount %> |
				 <%= link_to 'Edit', edit_employee_applied_loan_applied_loan_detail_path(@applied_loan.employee_id, @applied_loan, details) %> |
         <%= link_to 'Delete', [@applied_loan.employee, @applied_loan, details], confirm: 'Are you sure?', method: :delete %>
			</li>
	<% end %>
</ul>

app/views/applied_loans/_form.html.erb
<%= form_for([@applied_loan.employee,@applied_loan]) do |f| %>
  <% if @applied_loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applied_loan.errors.count, "error") %> prohibited this applied_loan from being saved:</h2>

      <ul>
      <% @applied_loan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.hidden_field :employee_id, :value=>params[:employee_id] %>
  <div class="field">
    <%= f.label :loan %>
    <%= f.collection_select :loan_id, Loan.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :date_started %>
    <%= f.date_select :date_started %>
  </div>
  
  <div class="field">
    <%= f.label :interval_type %>
    <% AppliedLoan.interval_types.each do |t| %>
	    
	    <%= f.radio_button :interval_type, t %> <%= t %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :original_amount, "Total Amount" %>
    <%= f.number_field :original_amount, :step=>0.01 %>
  </div>
  <div class="field">
    <%= f.label :amount_per_interval %>
    <%= f.number_field :amount_per_interval, :step=>0.01 %>
  </div>

  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applied_loans/_index.html.erb
<h1>Applied loans for <%= employee_full_name(params[:id]) %></h1>

<table border="1">
  <tr>
    
    <th>Loan</th>
    <th>Date started</th>
    <th>Date ended</th>
    <th>Interval Type</th>
    <th>Amount per interval</th>
    <th>Original amount</th>
    <th>Remaining balance</th>
    <th colspan="3"></th>
  </tr>

<% @applied_loans.each do |applied_loan| %>
  <tr>
   
    <td><%= applied_loan.loan.name %></td>
    <td><%= pretty_print_date(applied_loan.date_started) %></td>
    <td><%= pretty_print_date(applied_loan.date_ended) %></td>
    <td><%= applied_loan.interval_type %></td>
    <td><%= applied_loan.amount_per_interval %></td>
    <td><%= applied_loan.original_amount %></td>
    <td><%= applied_loan.remaining_balance %></td>
    <td><%= link_to 'Show', [applied_loan.employee,applied_loan] %></td>
    <td><%= link_to 'Edit', edit_employee_applied_loan_path(applied_loan.employee_id, applied_loan) %></td>
    <td><%= link_to 'Destroy', [applied_loan.employee, applied_loan], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>


app/views/applied_loans/edit.html.erb
<h1>Editing loan for <%= employee_full_name(params[:employee_id]) %></h1>

<%= render 'form' %>

<div class="extra">
	<%= link_to 'Show', [@applied_loan.employee, @applied_loan] %> |
	<%= link_to 'Back', employee_path(params[:employee_id]) %>
</div>

app/views/applied_loans/index.html.erb
<h1>Listing applied loans for <%= employee_full_name(params[:employee_id]) %></h1>

<table border="1">
  <tr>
    
    <th>Loan</th>
    <th>Date started</th>
    <th>Date ended</th>
    <th>Interval Type</th>
    <th>Amount per interval</th>
    <th>Original amount</th>
    <th>Remaining balance</th>
    <th colspan="3"></th>
  </tr>

<% @applied_loans.each do |applied_loan| %>
  <tr>
   
    <td><%= applied_loan.loan.name %></td>
    <td><%= pretty_print_date(applied_loan.date_started) %></td>
    <td><%= pretty_print_date(applied_loan.date_ended) %></td>
    <td><%= applied_loan.interval_type %></td>
    <td><%= applied_loan.amount_per_interval %></td>
    <td><%= applied_loan.original_amount %></td>
    <td><%= applied_loan.remaining_balance %></td>
    <td><%= link_to 'Show', [applied_loan.employee,applied_loan] %></td>
    <td><%= link_to 'Edit', edit_employee_applied_loan_path(applied_loan.employee_id, applied_loan) %></td>
    <td><%= link_to 'Destroy', [applied_loan.employee, applied_loan], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />
<div class="extra">
	<%= link_to 'New Applied loan', new_employee_applied_loan_path(params[:employee_id]) %> |
	<%= link_to 'Back', employee_path(params[:employee_id])%>
</div>

app/views/applied_loans/new.html.erb
<h1>New loan for <%= employee_full_name(params[:employee_id]) %></h1>

<%= render 'form' %>

<div class="extra">
	<%= link_to 'Back', employee_path(params[:employee_id]) %>
</div>

app/views/applied_loans/show.html.erb
<div class="show">

	<p id="notice"><%= notice %></p>

	<p>
		<b>Employee:</b>
		<%= @applied_loan.employee.complete_name %>
	</p>

	<p>
		<b>Loan:</b>
		<%= @applied_loan.loan.name %>
	</p>

	<p>
		<b>Date started:</b>
		<%= @applied_loan.date_started %>
	</p>

	<p>
		<b>Date ended:</b>
		<%= @applied_loan.date_ended %>
	</p>

	<p>
		<b>Interval Type:</b>
		<%= @applied_loan.interval_type %>
	</p>

	<p>
		<b>Amount per interval:</b>
		<%= @applied_loan.amount_per_interval %>
	</p>

	<p>
		<b>Original amount:</b>
		<%= @applied_loan.original_amount %>
	</p>

	<p>
		<b>Remaining balance:</b>
		<%= @applied_loan.remaining_balance %>
	</p>

	<%= render 'applied_loan_details' %>
</div>
<div class="extra">
	<%= link_to 'Edit', edit_employee_applied_loan_path(@applied_loan.employee, @applied_loan) %> |
	<%= link_to 'Back', employee_path(@applied_loan.employee) %>
</div>