config/routes.rb
Bayadligid::Application.routes.draw do
  get "applied_loan_details/index"

  get "applied_loan_details/new"

  get "applied_loan_details/edit"

  get "applied_loan_details/create"

  get "applied_loan_details/update"

  get "applied_loan_details/destroy"

  resources :companies do
  	resources :branches
  	resources :payrolls do
		member do
			get 'daily_payroll'
			get 'daily_payroll_details'
			get 'monthly_payroll'
			get 'monthly_payroll_details'
			get 'prooflist'
			get 'payslip'
			get 'two_by_two'
		end
	end
  end

  

  resources :loans
  resources :employees do
	  resources :applied_loans do
	    resources :applied_loan_details
	  end
  end

  resources :holidays do
  	collection do
  		get 'reset'
  	end
  end

  match '/:action', :controller => 'application'








  root :to => 'application#index'


end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer         not null, primary key
#  name       :string(255)     not null
#  created_at :datetime
#  updated_at :datetime
#

class Company < ActiveRecord::Base
	has_many :branches, :dependent=>:destroy
	has_many :payrolls, :dependent=>:destroy
	
	has_and_belongs_to_many :users
	
	validates_presence_of :name
	validates_uniqueness_of :name
	

	def employees
	  branch_ids = []
	  self.branches.each do |b|
	  	branch_ids << b.id
	  end
	  return Employee.where(:branch_id=>branch_ids).order([:branch_id,:last_name])
	end
	
	def employee_count
		employees.count
	end
	
	def latest_payroll
		Payroll.where(:company_id=>self.id).order(:date_started).last
  end
	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.joins(:users).where('users.id=?', session[:user_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.joins(:users).where('users.id=?', session[:user_id]).find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.joins(:users).where('users.id=?', session[:user_id]).find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])
	
    respond_to do |format|
      if @company.save
		User.find(session[:user_id]).companies << @company
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.joins(:users).where('users.id=?', session[:user_id]).find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.joins(:users).where('users.id=?', session[:user_id]).find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<div class="extra">
	<%= link_to 'Show', @company %> |
	<%= link_to 'Back', companies_path %>	
</div>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table border="1">
  <tr>
    <th>Name</th>
    <th>Branches</th>
    <th>Employees</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.branches.count %></td>
    <td><%= company.employee_count %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<div class="extra">
	<%= link_to 'New Company', new_company_path %>
</div>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<div class="extra">
	<%= link_to 'Back', companies_path %>
</div>

app/views/companies/show.html.erb
<div class="show">
	<p id="notice"><%= notice %></p>

	<p>
		<b>Name:</b>
		<%= @company.name %>
	</p>

	<p>
		<b>Branches:</b>
		<ul>
		<% for b in @company.branches %>
			<li> <%= link_to b.name, company_branch_url(@company,b) %> | <%= link_to 'Edit', edit_company_branch_url(@company, b) %> | <%= link_to 'Destroy', company_branch_path(@company, b), confirm: 'Are you sure?', method: :delete %></li>
		<% end %>
		</ul>
	</p>

	<%= link_to 'Add Branch', new_company_branch_path(@company) %>

	<p>
		<b>Employees:</b>
		<ul>
		<% for e in @company.employees %>
			<li> <%= link_to (e.first_name + " "+ e.last_name), e %> </li>
		<% end %>
		</ul>
	</p>
</div>
<div class="extra">
	<%= link_to 'Edit', edit_company_path(@company) %> |
	<%= link_to 'Back', companies_path %>
</div>